library(lubridate)
library(dplyr)
filePlotting <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(filePlotting, destfile = "./HPC.zip", method = "curl")
HPC <- read.csv("./household_power_consumption.txt", sep = ";")
names(HPC) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
fecha_hora <- paste(HPC$Date, HPC$Time, sep = " ")
HPC <- cbind(HPC, fecha_hora)
HPC$fecha_hora <- strptime(HPC$fecha_hora, "%d/%m/%Y %H:%M:%S")
HPC$Global_active_power <- as.numeric(HPC$Global_active_power)
HPC$Global_reactive_power <- as.numeric(HPC$Global_reactive_power)
HPC$Voltage <- as.numeric(HPC$Voltage)
HPC$Global_intensity <- as.numeric(HPC$Global_intensity)
HPC$Sub_metering_1 <- as.numeric(HPC$Sub_metering_1)
HPC$Sub_metering_2 <- as.numeric(HPC$Sub_metering_2)
HPC_fecha <- select(HPC, -(Date:Time))
subset_HPC <- filter(HPC_fecha, fecha_hora <= "2007-02-02 23:59:59" & fecha_hora >= "2007-02-01 00:00:00")
#Plot1
hist(subset_HPC$Global_active_power, main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot1.png", width = 480, height = 480, units = "px")
dev.off()